# Generated by Django 5.1.4 on 2025-01-13 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0001_initial'),
        ('developers', '0002_remove_developerprofile_developer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='developer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='developers.developerprofile'),
        ),
    ]
