# Generated by Django 5.1.4 on 2025-01-20 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0002_alter_building_developer'),
        ('maintenance_companies', '0003_rename_address_maintenancecompanyprofile_company_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='maintenance_company',
            field=models.ForeignKey(default='f314c931-b5e8-47b4-8a2f-1207a05cc057', on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='maintenance_companies.maintenancecompanyprofile'),
            preserve_default=False,
        ),
    ]
