# Generated by Django 5.1.4 on 2025-01-20 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0003_building_maintenance_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='maintenance_company',
        ),
    ]
