# Generated by Django 5.1.4 on 2025-01-09 09:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceCompanyProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(default='Unnamed Company', max_length=255)),
                ('address', models.CharField(default='Unknown Address', max_length=255)),
                ('registration_number', models.CharField(default='DEFAULT_REG', max_length=255)),
                ('specialization', models.CharField(default='Elevators', max_length=255)),
                ('maintenance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.maintenance')),
            ],
        ),
    ]
