# Generated by Django 5.1.4 on 2025-01-13 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance_companies', '0002_remove_maintenancecompanyprofile_maintenance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenancecompanyprofile',
            old_name='address',
            new_name='company_address',
        ),
    ]
