# Generated by Django 5.1.4 on 2025-01-26 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance_companies', '0003_rename_address_maintenancecompanyprofile_company_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancecompanyprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
