# Generated by Django 5.1.4 on 2025-01-09 09:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicianProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('technician', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='technician_profile', to='account.technician')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
