# Generated by Django 5.1.4 on 2025-01-13 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance_companies', '0002_remove_maintenancecompanyprofile_maintenance_and_more'),
        ('technicians', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technicianprofile',
            name='technician',
        ),
        migrations.AddField(
            model_name='technicianprofile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='technicianprofile',
            name='maintenance_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technicians', to='maintenance_companies.maintenancecompanyprofile'),
        ),
        migrations.AddField(
            model_name='technicianprofile',
            name='specialization',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='technicianprofile',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='technician_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
