# Generated by Django 5.1.4 on 2025-01-27 12:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0004_remove_building_maintenance_company'),
        ('elevators', '0004_alter_elevator_maintenance_company'),
        ('jobs', '0001_initial'),
        ('maintenance_companies', '0004_alter_maintenancecompanyprofile_user'),
        ('technicians', '0002_remove_technicianprofile_technician_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adhocmaintenancetask',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='maintenancecheck',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='maintenanceschedule',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='AdHocElevatorConditionReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_inspected', models.DateTimeField(default=django.utils.timezone.now)),
                ('components_checked', models.CharField(help_text='List of components or parts of the elevator inspected during this visit.', max_length=255)),
                ('condition', models.TextField(help_text='Condition of the components checked.')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_hoc_condition_reports', to='technicians.technicianprofile')),
            ],
            options={
                'verbose_name': 'Ad-Hoc Elevator Condition Report',
                'verbose_name_plural': 'Ad-Hoc Elevator Condition Reports',
            },
        ),
        migrations.CreateModel(
            name='AdHocMaintenanceSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField(help_text='Briefly describe the purpose of this ad-hoc schedule.')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('overdue', 'Overdue'), ('completed', 'Completed')], default='scheduled', max_length=20)),
                ('elevator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_hoc_schedules', to='elevators.elevator')),
                ('maintenance_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_hoc_schedules', to='maintenance_companies.maintenancecompanyprofile')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_hoc_schedules', to='technicians.technicianprofile')),
            ],
            options={
                'verbose_name': 'Ad-Hoc Maintenance Schedule',
                'verbose_name_plural': 'Ad-Hoc Maintenance Schedules',
            },
        ),
        migrations.CreateModel(
            name='AdHocMaintenanceLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_completed', models.DateTimeField(default=django.utils.timezone.now)),
                ('summary_title', models.CharField(help_text='Brief summary of the work done during this maintenance.', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('overseen_by', models.CharField(blank=True, max_length=255, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=255, null=True)),
                ('condition_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ad_hoc_maintenance_log', to='jobs.adhocelevatorconditionreport')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_hoc_maintenance_logs', to='technicians.technicianprofile')),
                ('ad_hoc_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='jobs.adhocmaintenanceschedule')),
            ],
            options={
                'verbose_name': 'Ad-Hoc Maintenance Log',
                'verbose_name_plural': 'Ad-Hoc Maintenance Logs',
            },
        ),
        migrations.AddField(
            model_name='adhocelevatorconditionreport',
            name='ad_hoc_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condition_reports', to='jobs.adhocmaintenanceschedule'),
        ),
        migrations.CreateModel(
            name='BuildingLevelAdhocSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField(help_text='Briefly describe the purpose of this ad-hoc schedule.')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('overdue', 'Overdue'), ('completed', 'Completed')], default='scheduled', max_length=20)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_level_adhoc_schedules', to='buildings.building')),
                ('maintenance_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_level_adhoc_schedules', to='maintenance_companies.maintenancecompanyprofile')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_level_adhoc_schedules', to='technicians.technicianprofile')),
            ],
            options={
                'verbose_name': 'Building Level Adhoc Schedule',
                'verbose_name_plural': 'Building Level Adhoc Schedules',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='ElevatorConditionReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_inspected', models.DateTimeField(default=django.utils.timezone.now)),
                ('alarm_bell', models.CharField(blank=True, max_length=255, null=True)),
                ('noise_during_motion', models.CharField(blank=True, max_length=255, null=True)),
                ('cabin_lights', models.CharField(blank=True, max_length=255, null=True)),
                ('position_indicators', models.CharField(blank=True, max_length=255, null=True)),
                ('hall_lantern_indicators', models.CharField(blank=True, max_length=255, null=True)),
                ('cabin_flooring', models.CharField(blank=True, max_length=255, null=True)),
                ('additional_comments', models.TextField(blank=True, null=True)),
                ('maintenance_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condition_reports', to='jobs.maintenanceschedule')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condition_reports', to='technicians.technicianprofile')),
            ],
            options={
                'verbose_name': 'Elevator Condition Report',
                'verbose_name_plural': 'Elevator Condition Reports',
            },
        ),
        migrations.CreateModel(
            name='ScheduledMaintenanceLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_completed', models.DateTimeField(default=django.utils.timezone.now)),
                ('check_machine_gear', models.BooleanField(default=False)),
                ('check_machine_brake', models.BooleanField(default=False)),
                ('check_controller_connections', models.BooleanField(default=False)),
                ('blow_dust_from_controller', models.BooleanField(default=False)),
                ('clean_machine_room', models.BooleanField(default=False)),
                ('clean_guide_rails', models.BooleanField(default=False)),
                ('observe_operation', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('overseen_by', models.CharField(blank=True, max_length=255, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=255, null=True)),
                ('condition_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_log', to='jobs.elevatorconditionreport')),
                ('maintenance_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='jobs.maintenanceschedule')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='technicians.technicianprofile')),
            ],
            options={
                'verbose_name': 'Scheduled Maintenance Log',
                'verbose_name_plural': 'Scheduled Maintenance Logs',
            },
        ),
        migrations.DeleteModel(
            name='MaintenanceLog',
        ),
    ]
