# Generated by Django 5.1.4 on 2025-02-09 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elevators', '0004_alter_elevator_maintenance_company'),
        ('jobs', '0002_alter_adhocmaintenancetask_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenanceschedule',
            options={'ordering': ['-scheduled_date'], 'verbose_name': 'Maintenance Schedule', 'verbose_name_plural': 'Maintenance Schedules'},
        ),
        migrations.AlterUniqueTogether(
            name='maintenanceschedule',
            unique_together={('elevator', 'scheduled_date')},
        ),
    ]
