# Generated by Django 5.1.4 on 2025-01-13 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_technician_maintenance_company_and_more'),
        ('buildings', '0002_alter_building_developer'),
        ('developers', '0002_remove_developerprofile_developer_and_more'),
        ('elevators', '0003_alter_elevator_developer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Developer',
        ),
    ]
