# Generated by Django 5.1.4 on 2025-02-04 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('TECH_SIGNUP', 'Technician Signup'), ('ELEVATOR_ASSIGNED', 'Elevator Assigned'), ('SCHEDULE_ASSIGNED', 'Schedule Assigned'), ('LOG_ADDED', 'Maintenance Log Added'), ('TASK_OVERDUE', 'Task Overdue'), ('TECH_UNLINK', 'Technician Unlinked'), ('ELEVATOR_REG', 'Elevator Registered'), ('BUILDING_REG', 'Building Registered')], max_length=50)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('recipient_id', models.PositiveIntegerField()),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_content', to='contenttypes.contenttype')),
                ('recipient_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_recipients', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient_type', 'recipient_id'], name='alerts_aler_recipie_73c804_idx'), models.Index(fields=['content_type', 'object_id'], name='alerts_aler_content_a9e91b_idx')],
            },
        ),
    ]
