# Generated by Django 5.1.4 on 2025-02-05 08:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'ordering': ['-created_at'], 'verbose_name': 'Alert', 'verbose_name_plural': 'Alerts'},
        ),
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('TECH_SIGNUP', 'Technician Signup'), ('ELEVATOR_ASSIGNED', 'Elevator Assigned'), ('SCHEDULE_ASSIGNED', 'Schedule Assigned'), ('LOG_ADDED', 'Maintenance Log Added'), ('TASK_OVERDUE', 'Task Overdue'), ('TECH_UNLINK', 'Technician Unlinked'), ('ELEVATOR_REG', 'Elevator Registered'), ('BUILDING_REG', 'Building Registered')], help_text='Type of alert being created', max_length=50),
        ),
        migrations.AlterField(
            model_name='alert',
            name='content_type',
            field=models.ForeignKey(help_text='Content type of the related object', on_delete=django.db.models.deletion.CASCADE, related_name='alert_content', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the alert was created'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='alert',
            name='is_read',
            field=models.BooleanField(default=False, help_text='Whether the alert has been read by the recipient'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='message',
            field=models.TextField(help_text='Alert message content'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='object_id',
            field=models.UUIDField(help_text='UUID of the related object'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='recipient_id',
            field=models.UUIDField(help_text='UUID of the recipient object'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='recipient_type',
            field=models.ForeignKey(help_text='Content type of the recipient', on_delete=django.db.models.deletion.CASCADE, related_name='alert_recipients', to='contenttypes.contenttype'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['created_at'], name='alerts_aler_created_8af5ce_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['is_read'], name='alerts_aler_is_read_ba5dfd_idx'),
        ),
    ]
