# Generated by Django 5.1.4 on 2025-02-07 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_alter_alert_options_alter_alert_alert_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('TECH_SIGNUP', 'Technician Signup'), ('ELEVATOR_ASSIGNED', 'Elevator Assigned'), ('SCHEDULE_ASSIGNED', 'Schedule Assigned'), ('LOG_ADDED', 'Maintenance Log Added'), ('TASK_OVERDUE', 'Task Overdue'), ('TECH_UNLINK', 'Technician Unlinked'), ('ELEVATOR_REG', 'Elevator Registered'), ('BUILDING_REG', 'Building Registered'), ('ADHOC_SCHEDULED', 'Ad-Hoc Maintenance Scheduled')], help_text='Type of alert being created', max_length=50),
        ),
    ]
