# Generated by Django 5.1.4 on 2025-02-13 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0005_alter_alert_alert_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('TECH_SIGNUP', 'Technician Signup'), ('ELEVATOR_ASSIGNED', 'Elevator Assigned'), ('SCHEDULE_ASSIGNED', 'Schedule Assigned'), ('LOG_ADDED', 'Maintenance Log Added'), ('TASK_OVERDUE', 'Task Overdue'), ('TECH_UNLINK', 'Technician Unlinked'), ('ELEVATOR_REG', 'Elevator Registered'), ('BUILDING_REG', 'Building Registered'), ('SCHEDULE_OVERDUE', 'Schedule Overdue'), ('ADHOC_SCHEDULED', 'Ad-Hoc Maintenance Scheduled'), ('TECH_UPDATED_BUILDING', 'Technician Updated for Building'), ('MAINTENANCE_APPROVAL', 'Maintenance Approval Needed')], help_text='Type of alert being created', max_length=50),
        ),
    ]
